// <auto-generated />
using System;
using Hamdlebot.Data.Contexts.Hamdlebot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hamdlebot.Data.Migrations
{
    [DbContext(typeof(HamdlebotContext))]
    partial class HamdlebotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hamdlebot.Data.Contexts.Hamdlebot.Entities.BotChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsHamdleEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hamdle_enabled");

                    b.HasKey("Id")
                        .HasName("pk_bot_channel");

                    b.HasIndex("ChannelId")
                        .IsUnique()
                        .HasAnnotation("idx_channel_id_unique", "true");

                    b.ToTable("bot_channel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
