services: 
  redis:
    container_name: "hamdle-redis"
    restart: unless-stopped
    image: "redis"
    volumes:
      - "hamdle-data:/redis"
  hamdle-web:
    container_name: "hamdlebot-web"
    restart: unless-stopped
    image: ghcr.io/nickyg91/hamdlebot-web:1.0.0
    environment:
      - Settings__ObsSettingsOptions__SocketUrl
      - Settings__ObsSettingsOptions__HamdleSourceName
      - Settings__ObsSettingsOptions__SceneName
      - Settings__ObsSettingsOptions__ObsAuthentication
    ports:
      - 8086:80
    depends_on: 
      redis:
        condition: service_started
  volumes:
    hamdle-data: