version: "3.8"
services: 
  redis:
    container_name: "hamdle-redis"
    restart: unless-stopped
    image: "redis"
    volumes:
      - "hamdle-data:/redis"
  hamdle-web:
    container_name: "hamdlebot-web"
    restart: unless-stopped
    image: ghcr.io/nickyg91/hamdlebot-web:1.0.0
    env_file:
      - ~/docker-env/.hamdlebot-env
    ports:
      - 8086:8080
    depends_on: 
      redis:
        condition: service_started
  hamdle-insights:
    container_name: "hamdle-insights"
    restart: unless-stopped
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    ports:
      - 18888:18888
      - 4317:18889
    depends_on: 
      hamdle-web:
        condition: service_started
volumes:
  hamdle-data:
