name: Build and Publish Hamdlebot Containers
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hamdlebot-web

on:
  push:
    branches: ["main"]

jobs:
  build-web:
    name: Build Hamdlebot Web Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      HAMDLEBOT_WEB_IMAGE_NAME: hamdlebot-web

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.HAMDLEBOT_WEB_IMAGE_NAME }}

      - name: Build and push Hamdlebot Web
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./src/Hamdlebot
          push: true
          tags: ghcr.io/${{github.repository_owner}}/hamdlebot-web:1.0.0
          labels: ${{ steps.meta.outputs.labels }}
          file: ./src/Hamdlebot/Hamdlebot.Web/Dockerfile
  deploy-container:
    name: Deploy Hamdlebot Web Container
    needs: build-web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Execute ssh commands to pull down repo and run docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HYPERION_HOSTNAME}}
          username: ${{secrets.DEPLOY_USER}}
          key: ${{secrets.DEPLOY_SSH_KEY}}
          script: |
            rm -rf hamdlebot
            gh repo clone nickyg91/hamdlebot
            docker login ghcr.io -u ${{github.actor}} --password ${{ secrets.GITHUB_TOKEN }}
            cd hamdlebot/src/Hamdlebot
            cp docker-compose.yml ~/docker-env && cd ~/docker-env
            docker-compose down
            docker-compose pull
            rm -rf docker-compose.yml